app/analise_avaliacoes/config/routes.rb
Rails.application.routes.draw do
  resources :avaliacoes
  resources :produtos
      root to: 'dashboard#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "carrega_avaliacoes/:produto_id", to: "produtos#carrega_avaliacoes", as:"carrega_avaliacoes"
  get "carga_produtos_avaliacoes", to: "dashboard#carga_produtos_avaliacoes", as:"carga_produtos_avaliacoes"
  post 'avaliacoes/avaliacoes_por_csv(/:produto_id)', to: 'avaliacoes#avaliacoes_por_csv', as: 'avaliacoes_por_csv'
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/analise_avaliacoes/app/controllers/avaliacoes_controller.rb
  require 'csv'
  require 'net/http'
  require 'json'

  class AvaliacoesController < ApplicationController
    before_action :set_avaliacao, only: %i[ show edit update destroy ]
  
    # GET /avaliacoes
    def index
      @q = Avaliacao.ransack(params[:q])
      @pagy, @avaliacoes = pagy(
        @q.result, items: 10 
      )
    end
  
    def show; end
  
    def new
      @avaliacao = Avaliacao.new
    end
  
    def edit; end
  
    def create
      @avaliacao = Avaliacao.new(avaliacao_params)
  
      if @avaliacao.save
        redirect_to @avaliacao
        flash[:success] = t("#{}.created") 
      else
        render :new, status: :unprocessable_entity
        flash[:error] = t("#{}.no_created")
      end
    end
  
    def update
      if @avaliacao.update(avaliacao_params)
        redirect_to @avaliacao
        flash[:success] = t("#{}.updated")  
      else
        render :edit, status: :unprocessable_entity
        flash[:error] = t("#{}.no_updated")
      end
    end
  
    def destroy
      if  @avaliacao.destroy!
        redirect_to avaliacoes_url
        flash[:success] = t("#{}.deleted")   
      else 
        redirect_to @avaliacao
        flash[:error] = t("#{}.no_deleted")   
      end
    end

    def avaliacoes_por_csv
      produto_id = params[:produto_id]
      produtos_e_avaliacoes = params[:produtos_e_avaliacoes] == "true" ? true : false
      uploaded_file = params[:file]
  
      if produto_id.nil? && !produtos_e_avaliacoes
        flash[:error] = "Produto não encontrado."
        redirect_to request.referer and return
      end
  
      if uploaded_file.nil?
        flash[:error] = "Por favor, selecione um arquivo CSV para enviar."
        redirect_to request.referer and return
      end
  
      Avaliacoes::CarregaCsvService.call(uploaded_file.path, produto_id);

      flash[:success] = "Arquivo CSV processado com sucesso para o produto ##{produto_id}!"
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_avaliacao
        @avaliacao = Avaliacao.find(params[:id])
      end
  
      def avaliacao_params
        params.require(:avaliacao).permit(:texto, :sentimento, :produto_id)
      end
  end
  

app/analise_avaliacoes/app/views/avaliacoes/_avaliacao.html.erb
<div id="<%= dom_id avaliacao %>">
  <p>
    <strong>Texto:</strong>
    <%= avaliacao.texto %>
  </p>

  <p>
    <strong>Sentimento:</strong>
    <%= avaliacao.sentimento %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= avaliacao.produto_id %>
  </p>

</div>

app/analise_avaliacoes/app/views/avaliacoes/_form.html.erb
<div class="card">
  <%= simple_form_for @avaliacao do |f| %>
    <%= f.error_notification %>
    <div class="card-body"> 
      <p class="card-text">
        <div class="row">
        
          <div class="col-md-6">
            <%= f.input :texto,
              label: t('activerecord.attributes.avaliacao.texto'),
              input_html: {maxlength: 20} %>
          </div>
        
          <div class="col-md-6">
            <%= f.input :sentimento,
              label: t('activerecord.attributes.avaliacao.sentimento'),
              input_html: {maxlength: 20} %>
          </div>
        
          <div class="col-md-6">
            <%= f.input :produto_id,
              label: t('activerecord.attributes.avaliacao.produto_id'),
              input_html: {maxlength: 20} %>
          </div>
        
        </div>
      </p>
    </div>
    <div class="card-footer">
      <div class="d-flex justify-content-end">
        <%= btn_submit @avaliacao.new_record? %>
        <%= btn_voltar %>
      </div>
    </div>
  <% end %>
</div>

app/analise_avaliacoes/app/views/avaliacoes/edit.html.erb
<% content_for :area_info do %>
  <div class="panel panel-flat">
    <div class="panel-heading">
      <h3 class="panel-title"><i class="<%= icone_edit %> position-left"></i><%= t('avaliacoes.edit') %></h3>
      <div class="heading-elements">
      </div>
    </div>
  </div>
<% end %>

<%= render 'form' %>

app/analise_avaliacoes/app/views/avaliacoes/index.html.erb
<div class="card"  style="margin-bottom: 10px;">
  <div class="card-body">
    <h3 class="card-title">
      <i class="<%= icone_search %> position-left"></i>
      <%= t 'helpers.pesquisa' %>
    </h3>
    <p class="card-text">
      <%= search_form_for @q, url: avaliacoes_path do |f| %>
        <div class="row">
          
            <div class="col-md-4">
              <div class="form-group">
                <%= f.search_field :texto_cont,
                  placeholder: t('activerecord.attributes.avaliacao.texto'),
                  class: 'form-control busca_ransack', maxlength: 10 %>
              </div>
            </div>
          
            <div class="col-md-3">
              <div class="form-group">
                <%= f.search_field :sentimento_cont,
                  placeholder: t('activerecord.attributes.avaliacao.sentimento'),
                  class: 'form-control busca_ransack', maxlength: 10 %>
              </div>
            </div>
          
            <div class="col-md-4">
              <div class="form-group">
                <%= f.search_field :produto_id_cont,
                  placeholder: t('activerecord.attributes.avaliacao.produto_id'),
                  class: 'form-control busca_ransack', maxlength: 10 %>
              </div>
            </div>
          
          <div class="col-md-1">
            <button name="button" type="submit" class="btn btn-primary right center_on_mobile legitRipple">
              <span><%= t 'acoes.buscar' %></span>
            </button>
          </div>
        </div>
      <% end %>
    </p>
  </div>
</div>

<div class="card h-100">
  <div class="card-body">
    <h3 class="card-title d-flex justify-content-between">
      <%= t 'activerecord.models.avaliacao'.pluralize.titleize %>
      <%= btn_novo t('avaliacoes.new'), new_avaliacao_path %>
    </h3>
    <p class="card-text">
      <div class="table-responsive">
        <table class="<%= tabela_padrao_class %>">
          <thead>
          <tr>
            <th><%= t 'activerecord.attributes.avaliacao.texto' %></th>
            <th><%= t 'activerecord.attributes.avaliacao.sentimento' %></th>
            <th><%= t 'activerecord.attributes.avaliacao.produto_id' %></th>
            <th class="text-center">
              <%= t 'activerecord.attributes.acoes' %>
            </th>
          </tr>
          </thead>
          <tbody>
            <% @avaliacoes.each do |objeto| %>
              <tr>
                
                  <td><%= objeto.texto %></td>
                
                  <td><%= objeto.sentimento %></td>
                
                  <td><%= objeto.produto_id %></td>
                
                  <td class="text-center">
                    <%= btn_visualizar(avaliacao_path(objeto)) %>
                    <%= btn_editar(edit_avaliacao_path(objeto), label: '') %>
                    <%= btn_excluir(avaliacao_path(objeto)) %>
                  </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <% if @avaliacoes.count == 0 %>
        <blockquote>Nenhum registro encontrado.</blockquote>
      <% end %>
    </p>
  </div>
  <div class="card-footer">
    <%= render 'shared/pagy_paginacao' %>
  </div>
</div>

app/analise_avaliacoes/app/views/avaliacoes/new.html.erb
<% content_for :area_info do %>
  <div class="panel panel-flat">
    <div class="panel-heading">
      <h3 class="panel-title"><i class="<%= icone_new %> position-left"></i><%= t('avaliacoes.new') %></h3>
      <div class="heading-elements">
      </div>
    </div>
  </div>
<% end %>

<%= render 'form' %>

app/analise_avaliacoes/app/views/avaliacoes/show.html.erb
<% content_for :area_info do %>
  <div class="card">
    <div class="card-header d-flex justify-content-between">
      <h3 class="card-text">
        <i class="<%= icone_show %>"></i>
        <%= @avaliacao %>
      </h3>
      <div class="heading-elements">
        <%= btn_editar edit_avaliacao_url(@avaliacao), type: 'heading' %>
      </div>
    </div>
  </div>
<% end %>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <dl>
          <dt><%= t 'activerecord.attributes.avaliacao.texto' %></dt>
          <dd><%= @avaliacao.texto %></dd>
        </dl>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <dl>
          <dt><%= t 'activerecord.attributes.avaliacao.sentimento' %></dt>
          <dd><%= @avaliacao.sentimento %></dd>
        </dl>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <dl>
          <dt><%= t 'activerecord.attributes.avaliacao.produto_id' %></dt>
          <dd><%= @avaliacao.produto_id %></dd>
        </dl>
      </div>
    </div>
    <hr>
    
  </div>
  <div class="card-footer d-flex flex-row-reverse">
    <%= btn_voltar %>
  </div>
</div>